name: image-build

on:
  push:
    branches: main

    inputs:
      image_repository:
        description: The ECR image repository name
        required: false
        type: string
        default: clickdealer-themes/rclone-conf

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::353817990488:role/github-actions
        aws-region: eu-west-2
        mask-aws-account-id: false

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: eu-west-2

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_repository }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        repository: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_repository }}
        push: true
        context: .
        tags: latest